### ISSUE TITLE
Custom channels

### ISSUE THREAD

**Issue by Philanatidae** [mini2Dx/gradle-butler-plugin#1]
Currently the plugin doesn't support having custom channels, it only pushes to the channel specific to the system. For an HTML game the channel isn't platform specific. It would be a great improvement to have the ability to have custom channels that are platform independent, or to have games pushed to beta channels.

**Comment by tomcashman** [comment]
I'll add this soon :)

**Comment by tomcashman** [comment]
Available now in 1.1.0 :)
